version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    env_file: .env
    ports:
      - "3307:3307"

volumes:
  db_vol:
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: ${MYSQL_VOLUME}