version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    restart: always
    env_file:
      - .env
    tty: true
    networks:
      - inception
  nginx:
    depends_on:
      - wordpress
    image: debian:buster # to replace with build
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    tty: true
    networks:
      - inception
    
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    tty: true
    networks:
      - inception
volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MYSQL_VOLUME}
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${WORDPRESS_VOLUME}
networks:
  inception:
